apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io